// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiastaNet.API.Data;

#nullable disable

namespace PiastaNet.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222205634_FixGameEvents")]
    partial class FixGameEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiastaNet.API.Models.Boardgame", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double?>("BggAverageRating")
                        .HasColumnType("float");

                    b.Property<int?>("BggId")
                        .HasColumnType("int");

                    b.Property<int?>("BggRank")
                        .HasColumnType("int");

                    b.Property<double?>("BggRating")
                        .HasColumnType("float");

                    b.Property<int?>("LearnDifficulty")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("PlayDifficulty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("boardgames", (string)null);
                });

            modelBuilder.Entity("PiastaNet.API.Models.Category", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.HasKey("ItemId", "Name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PiastaNet.API.Models.GameEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("MaxNumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinNumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("PiastaNet.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Copies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("No description provided");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Thumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("https://i.imgur.com/OJhoTqu.png");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("PiastaNet.API.Models.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("Platform")
                        .HasColumnType("int");

                    b.Property<int>("PlayingTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("videogames", (string)null);
                });

            modelBuilder.Entity("PiastaNet.API.Models.Boardgame", b =>
                {
                    b.HasOne("PiastaNet.API.Models.Item", "Item")
                        .WithOne("Boardgame")
                        .HasForeignKey("PiastaNet.API.Models.Boardgame", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PiastaNet.API.Models.Category", b =>
                {
                    b.HasOne("PiastaNet.API.Models.Item", "Item")
                        .WithMany("Categories")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PiastaNet.API.Models.GameEvent", b =>
                {
                    b.HasOne("PiastaNet.API.Models.Item", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PiastaNet.API.Models.Videogame", b =>
                {
                    b.HasOne("PiastaNet.API.Models.Item", "Item")
                        .WithOne("Videogame")
                        .HasForeignKey("PiastaNet.API.Models.Videogame", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PiastaNet.API.Models.Item", b =>
                {
                    b.Navigation("Boardgame");

                    b.Navigation("Categories");

                    b.Navigation("GameEvents");

                    b.Navigation("Videogame");
                });
#pragma warning restore 612, 618
        }
    }
}
