name: Deploy to Azure

on:
  push:
    branches: [ main ]
  
    # Ignore changes in the 'infra' directory to prevent unnecessary deployments
    paths-ignore: 'infra/**'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: dotnet build ${{ vars.BACKEND_PATH }}/${{ vars.BACKEND_BUILD_FILE }} --configuration Release
      
    - name: Publish
      run: dotnet publish ${{ vars.BACKEND_PATH }}/${{ vars.BACKEND_BUILD_FILE }} -c Release -o ./publish
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'piasta-net-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
